version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: nginx-redis-webserver
    ports:
      - 80:80
    volumes:
      - ./jph-reverse-proxy.conf:/etc/nginx/jph-reverse-proxy.conf
      - ./jph-reverse-proxy-load-balancer.conf:/etc/nginx/jph-reverse-proxy-load-balancer.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
  redis:
    container_name: nginx-redis-tutorial
    image: redis:7.0
    ports:
      - 6379:6379
  node:
    image: node-application
    build: 
      context: .
      dockerfile: ./node/Dockerfile
    ports:
      - 3001:3001

# present perfect tense
# based in
# join client
# english past verbs
# little period of time (uncountable)
# few (countable)